### PR TITLE
Committing SSO support changes to common js client

### PR DESCRIPTION
**Pull request by prachipalaskar23**
(Fixed [AB#2519](https://dev.azure.com/CxSDLC/fc0b9449-79c8-4ff2-bd04-b9e18cf01a53/_workitems/edit/2519))

### Description

1) Supported SSO login for VSCode Plugin
2) When user tried to Login to SAST application he can select SSO login option
3) On click of SSO login option VSCode plugin redirects user to Login page of SAST application  in browser
4) After giving credentials browser will redirect user to VSCode with authorization token
5) With this authorization token user will be logged in.

### CODE REVIEW

**Review by sangamchitmugre — APPROVED** [review]
As Per typescript it looks good

**Review by SubhadraSahoo — COMMENTED** [review]
Still the updated PR is showing  workspace.code-workspace  being checked in. Please check it.

**Review by SubhadraSahoo — APPROVED** [review]
Looks good

**Comment by prachipalaskar23** [comment]
Merging changes to integration branch

**Pull request merged**
